import Chip from "@mui/material/Chip";
import { GridRowsProp, GridColDef } from "@mui/x-data-grid";

function renderStatus(status: "Approved" | "Pending" | "UnApproved") {
  const colors: { [index: string]: "success" | "default" | "error" } = {
    Approved: "success",
    Pending: "default",
    UnApproved: "error",
  };

  return <Chip label={status} color={colors[status]} size="small" />;
}


export const columns: GridColDef[] = [
  { field: "Name", headerName: "Name", flex: 1.5, minWidth: 100 },
  {
    field: "projectName",
    headerName: "Project Name",
    headerAlign: "left",
    align: "left",
    flex: 1,
    minWidth: 300,
  },
  {
    field: "status",
    headerName: "Status",
    flex: 0.5,
    minWidth: 100,
    renderCell: (params) => renderStatus(params.value as any),
  },
  {
    field: "appliedDate",
    headerName: "Applied Date",
    headerAlign: "right",
    align: "right",
    flex: 1,
    minWidth: 100,
  },
  {
    field: "approvedDate",
    headerName: "Approved Date",
    headerAlign: "right",
    align: "right",
    flex: 1,
    minWidth: 120,
  },
  {
    field: "batchYear",
    headerName: "Batch",
    headerAlign: "right",
    align: "right",
    flex: 1,
    minWidth: 100,
  },
];

export const rows: GridRowsProp = [
  {
    id: 1,
    Name: "Amit Sharma",
    status: "Approved",
    projectName: "AI-Powered Chatbot",
    appliedDate: 212423,
    approvedDate: 18.5,
    batchYear: 2015,
  },
  {
    id: 2,
    Name: "Rohit Kumar",
    status: "Approved",
    projectName: "E-Learning Platform",
    appliedDate: 212425,
    approvedDate: 20.3,
    batchYear: 2016,
  },
  {
    id: 3,
    Name: "Priya Nair",
    status: "UnApproved",
    projectName: "Blockchain-Based Voting System",
    appliedDate: 212427,
    approvedDate: 19.1,
    batchYear: 2017,
  },
  {
    id: 4,
    Name: "Sneha Gupta",
    status: "Approved",
    projectName: "Inventory Management System",
    appliedDate: 212429,
    approvedDate: 21.4,
    batchYear: 2018,
  },
  {
    id: 5,
    Name: "Arjun Menon",
    status: "Pending",
    projectName: "Real-Time Weather App",
    appliedDate: 212431,
    approvedDate: 22.7,
    batchYear: 2019,
  },
  {
    id: 6,
    Name: "Ritu Singh",
    status: "Approved",
    projectName: "IoT Smart Home System",
    appliedDate: 212433,
    approvedDate: 23.8,
    batchYear: 2020,
  },
  {
    id: 7,
    Name: "Vikram Joshi",
    status: "Pending",
    projectName: "Online Food Delivery System",
    appliedDate: 212435,
    approvedDate: 24.2,
    batchYear: 2021,
  },
  {
    id: 8,
    Name: "Meera Iyer",
    status: "Approved",
    projectName: "Healthcare Management System",
    appliedDate: 212437,
    approvedDate: 25.3,
    batchYear: 2022,
  },
  {
    id: 9,
    Name: "Karthik Reddy",
    status: "Pending",
    projectName: "Mobile Expense Tracker App",
    appliedDate: 212439,
    approvedDate: 26.5,
    batchYear: 2023,
  },
  {
    id: 10,
    Name: "Neha Patel",
    status: "Approved",
    projectName: "Travel Booking System",
    appliedDate: 212441,
    approvedDate: 27.9,
    batchYear: 2024,
  },
  {
    id: 11,
    Name: "Siddharth Jain",
    status: "Approved",
    projectName: "Personal Finance Dashboard",
    appliedDate: 212443,
    approvedDate: 28.1,
    batchYear: 2025,
  },
  {
    id: 12,
    Name: "Deepak Yadav",
    status: "Pending",
    projectName: "Virtual Reality Gaming App",
    appliedDate: 212445,
    approvedDate: 29.3,
    batchYear: 2026,
  },
  {
    id: 13,
    Name: "Anjali Verma",
    status: "Approved",
    projectName: "Cybersecurity Threat Detector",
    appliedDate: 212447,
    approvedDate: 30.5,
    batchYear: 2027,
  },
  {
    id: 14,
    Name: "Rajesh Pillai",
    status: "UnApproved",
    projectName: "Social Media Management Tool",
    appliedDate: 212449,
    approvedDate: 31.7,
    batchYear: 2028,
  },
  {
    id: 15,
    Name: "Pooja Chawla",
    status: "Approved",
    projectName: "Language Translation App",
    appliedDate: 212451,
    approvedDate: 32.9,
    batchYear: 2029,
  },
  {
    id: 16,
    Name: "Manish Tiwari",
    status: "Pending",
    projectName: "Crowdsourced Fundraising Platform",
    appliedDate: 212453,
    approvedDate: 33.2,
    batchYear: 2030,
  },
  {
    id: 17,
    Name: "Shreya Das",
    status: "Approved",
    projectName: "Employee Attendance Tracker",
    appliedDate: 212455,
    approvedDate: 34.4,
    batchYear: 2031,
  },
  {
    id: 18,
    Name: "Nitin Bansal",
    status: "Approved",
    projectName: "Digital Library Management System",
    appliedDate: 212457,
    approvedDate: 35.6,
    batchYear: 2032,
  },
  {
    id: 19,
    Name: "Isha Malhotra",
    status: "UnApproved",
    projectName: "Customer Feedback Analyzer",
    appliedDate: 212459,
    approvedDate: 36.8,
    batchYear: 2033,
  },
  {
    id: 20,
    Name: "Kabir Singh",
    status: "Pending",
    projectName: "AI-Based Resume Screener",
    appliedDate: 212461,
    approvedDate: 37.0,
    batchYear: 2034,
  },
];
